-- Supabase SQL Schema for Customer Support System
-- Paste this entire file into the Supabase SQL Editor and click "Run"

-- 1. Create Customers Table
CREATE TABLE IF NOT EXISTS customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    age INT,
    gender TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    total_orders INT DEFAULT 0,
    open_tickets INT DEFAULT 0,
    avg_satisfaction FLOAT
);

-- 2. Create Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    price DECIMAL(10, 2),
    stock INT DEFAULT 0,
    description TEXT
);

-- 3. Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
    order_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT DEFAULT 'active',
    tracking_number TEXT
);

-- 4. Create Tickets Table
CREATE TABLE IF NOT EXISTS tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
    subject TEXT NOT NULL,
    description TEXT NOT NULL,
    type TEXT DEFAULT 'inquiry',
    status TEXT DEFAULT 'open',
    priority TEXT DEFAULT 'medium',
    channel TEXT DEFAULT 'chat',
    assigned_agent TEXT,
    resolution TEXT,
    satisfaction_rating INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    closed_at TIMESTAMP WITH TIME ZONE
);

-- 5. Create Conversations Table
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT UNIQUE NOT NULL,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
    ticket_id BIGINT REFERENCES tickets(id) ON DELETE SET NULL,
    transcript JSONB,
    escalated BOOLEAN DEFAULT FALSE,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ended_at TIMESTAMP WITH TIME ZONE
);

-- 6. Lock down public tables for Supabase Data API access
-- The Next.js frontend calls the FastAPI backend, not Supabase directly.
-- Keep customer data server-side by denying anon/authenticated roles and
-- allowing the backend service key to perform required operations.
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.customers FROM anon, authenticated;
REVOKE ALL ON public.products FROM anon, authenticated;
REVOKE ALL ON public.orders FROM anon, authenticated;
REVOKE ALL ON public.tickets FROM anon, authenticated;
REVOKE ALL ON public.conversations FROM anon, authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.customers TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.orders TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tickets TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.conversations TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
-- Create Idempotency Table
CREATE TABLE IF NOT EXISTS idempotency_records (
    customer_id BIGINT NOT NULL,
    client_request_id UUID NOT NULL,
    operation_type TEXT NOT NULL,
    canonical_target TEXT NOT NULL,
    payload_hash TEXT NOT NULL,
    terminal_result JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (customer_id, client_request_id)
);

ALTER TABLE public.idempotency_records ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.idempotency_records FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.idempotency_records TO service_role;

-- Generic RPC to execute idempotent operations
CREATE OR REPLACE FUNCTION execute_idempotent_operation(
    p_customer_id BIGINT,
    p_client_request_id UUID,
    p_operation_type TEXT,
    p_canonical_target TEXT,
    p_payload_hash TEXT,
    p_payload JSONB
) RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_existing_type TEXT;
    v_existing_target TEXT;
    v_existing_hash TEXT;
    v_existing_result JSONB;
    v_result JSONB;
    
    -- Variables for specific operations
    v_ticket_id BIGINT;
    v_order_status TEXT;
    v_order_customer_id BIGINT;
    v_existing_desc TEXT;
    v_timestamp TEXT;
    v_ticket_owner BIGINT;
BEGIN
    -- 1. Concurrency control: attempt to select existing record with lock
    SELECT operation_type, canonical_target, payload_hash, terminal_result
    INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
    FROM idempotency_records
    WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id
    FOR UPDATE;

    IF FOUND THEN
        -- Conflict check
        IF v_existing_type != p_operation_type OR v_existing_target != p_canonical_target OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object(
                'error', 'IdempotencyConflict',
                'message', 'This request ID was already used for a different operation.',
                'previous_result', v_existing_result
            );
        END IF;
        -- Exact retry: return cached result
        RETURN v_existing_result;
    END IF;

    -- 2. Insert to establish operation and claim the request_id.
    -- If a concurrent transaction already inserted it, this throws unique_violation.
    BEGIN
        INSERT INTO idempotency_records (
            customer_id, client_request_id, operation_type, canonical_target, payload_hash
        ) VALUES (
            p_customer_id, p_client_request_id, p_operation_type, p_canonical_target, p_payload_hash
        );
    EXCEPTION WHEN unique_violation THEN
        -- Block until the winning concurrent transaction commits or rolls back
        SELECT operation_type, canonical_target, payload_hash, terminal_result
        INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
        FROM idempotency_records
        WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id
        FOR UPDATE;
        
        IF v_existing_type != p_operation_type OR v_existing_target != p_canonical_target OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object(
                'error', 'IdempotencyConflict',
                'message', 'This request ID was already used for a different operation.',
                'previous_result', v_existing_result
            );
        END IF;
        RETURN v_existing_result;
    END;

    -- 3. Execute business logic based on operation_type
    IF p_operation_type = 'create_ticket' THEN
        INSERT INTO tickets (
            customer_id, subject, description, type, status, priority, channel, order_id
        ) VALUES (
            p_customer_id,
            p_payload->>'subject',
            p_payload->>'description',
            p_payload->>'type',
            p_payload->>'status',
            p_payload->>'priority',
            p_payload->>'channel',
            (p_payload->>'order_id')::BIGINT
        ) RETURNING id INTO v_ticket_id;
        
        v_result := jsonb_build_object(
            'status', 'success',
            'message', 'Ticket #' || v_ticket_id || ' created successfully',
            'ticket_id', v_ticket_id
        );

    ELSIF p_operation_type = 'update_ticket' THEN
        v_ticket_id := p_canonical_target::BIGINT;
        
        -- Check ownership and existence
        SELECT customer_id, description INTO v_ticket_owner, v_existing_desc
        FROM tickets WHERE id = v_ticket_id;
        
        IF NOT FOUND OR v_ticket_owner != p_customer_id THEN
            v_result := jsonb_build_object('error', 'Ticket #' || v_ticket_id || ' not found or does not belong to you');
        ELSE
            -- We only support description_append, priority, order_id here as per python logic
            IF p_payload ? 'description_append' THEN
                -- Format timestamp like python did: YYYY-MM-DD HH:MM:SS UTC
                v_timestamp := to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS "UTC"');
                v_existing_desc := COALESCE(v_existing_desc, '') || E'\n\n--- Update (' || v_timestamp || E') ---\n' || (p_payload->>'description_append');
            END IF;
            
            UPDATE tickets SET 
                description = v_existing_desc,
                priority = COALESCE(p_payload->>'priority', priority),
                order_id = COALESCE((p_payload->>'order_id')::BIGINT, order_id),
                updated_at = now()
            WHERE id = v_ticket_id;
            
            v_result := jsonb_build_object('status', 'success', 'message', 'Ticket #' || v_ticket_id || ' updated');
        END IF;

    ELSIF p_operation_type = 'cancel_order' THEN
        -- canonical_target is order_id
        SELECT status, customer_id INTO v_order_status, v_order_customer_id
        FROM orders WHERE id = p_canonical_target::BIGINT FOR UPDATE;
        
        IF NOT FOUND OR v_order_customer_id != p_customer_id THEN
            v_result := jsonb_build_object('error', 'Order #' || p_canonical_target || ' not found or does not belong to you');
        ELSIF v_order_status != 'active' THEN
            v_result := jsonb_build_object('error', 'Cannot cancel order #' || p_canonical_target || '. Current status: ' || v_order_status || '. Only active orders can be cancelled.');
        ELSE
            UPDATE orders SET status = 'cancelled' WHERE id = p_canonical_target::BIGINT;
            v_result := jsonb_build_object('status', 'success', 'message', 'Order #' || p_canonical_target || ' has been cancelled');
        END IF;

    ELSIF p_operation_type = 'process_refund' THEN
        SELECT status, customer_id INTO v_order_status, v_order_customer_id
        FROM orders WHERE id = p_canonical_target::BIGINT FOR UPDATE;
        
        IF NOT FOUND OR v_order_customer_id != p_customer_id THEN
            v_result := jsonb_build_object('error', 'Order #' || p_canonical_target || ' not found or does not belong to you');
        ELSIF v_order_status NOT IN ('cancelled', 'delivered') THEN
            v_result := jsonb_build_object('error', 'Cannot refund order #' || p_canonical_target || '. Current status: ' || v_order_status || '. Order must be cancelled or delivered.');
        ELSE
            UPDATE orders SET status = 'refunded' WHERE id = p_canonical_target::BIGINT;
            v_result := jsonb_build_object('status', 'success', 'message', 'Refund initiated for order #' || p_canonical_target || '. The refund will be processed within 5-7 business days.');
        END IF;
    ELSE
        v_result := jsonb_build_object('error', 'Unknown operation type: ' || p_operation_type);
    END IF;

    -- 4. Save the terminal result
    UPDATE idempotency_records 
    SET terminal_result = v_result
    WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id;

    RETURN v_result;
END;
$$;

REVOKE EXECUTE ON FUNCTION execute_idempotent_operation FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION execute_idempotent_operation TO service_role;


-- 7. Outbox Schema for Email Notifications (Slice 3.2)
CREATE TABLE IF NOT EXISTS outbox_events (
    event_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    logical_identity_hash TEXT UNIQUE NOT NULL,
    source_event_id TEXT NOT NULL,
    notification_type TEXT NOT NULL,
    recipient_identity TEXT NOT NULL,
    recipient_address TEXT NOT NULL,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    claim_token UUID,
    claimed_at TIMESTAMP WITH TIME ZONE,
    next_attempt_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    sent_at TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT valid_status CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'RETRYABLE', 'FAILED'))
);

-- Index for worker polling
CREATE INDEX IF NOT EXISTS idx_outbox_events_poll 
ON outbox_events(status, next_attempt_at) 
WHERE status IN ('PENDING', 'RETRYABLE');

ALTER TABLE public.outbox_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.outbox_events FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.outbox_events TO service_role;

-- Enqueue Function
CREATE OR REPLACE FUNCTION enqueue_outbox_event(
    p_logical_identity_hash TEXT,
    p_source_event_id TEXT,
    p_notification_type TEXT,
    p_recipient_identity TEXT,
    p_recipient_address TEXT,
    p_payload JSONB
) RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_event_id UUID;
    v_status TEXT;
BEGIN
    INSERT INTO outbox_events (
        logical_identity_hash, source_event_id, notification_type, 
        recipient_identity, recipient_address, payload, status
    ) VALUES (
        p_logical_identity_hash, p_source_event_id, p_notification_type, 
        p_recipient_identity, p_recipient_address, p_payload, 'PENDING'
    )
    ON CONFLICT (logical_identity_hash) DO NOTHING
    RETURNING event_id INTO v_event_id;

    IF v_event_id IS NULL THEN
        -- It was a duplicate
        SELECT event_id, status INTO v_event_id, v_status
        FROM outbox_events
        WHERE logical_identity_hash = p_logical_identity_hash;

        RETURN jsonb_build_object(
            'status', 'duplicate',
            'event_id', v_event_id,
            'current_status', v_status
        );
    ELSE
        RETURN jsonb_build_object(
            'status', 'enqueued',
            'event_id', v_event_id,
            'current_status', 'PENDING'
        );
    END IF;
END;
$$;

REVOKE EXECUTE ON FUNCTION enqueue_outbox_event FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION enqueue_outbox_event TO service_role;



-- 8. Ticket Notification Wrapper RPC (Slice 3.4)
CREATE OR REPLACE FUNCTION execute_ticket_mutation_with_outbox(
    p_customer_id BIGINT,
    p_client_request_id UUID,
    p_operation_type TEXT,
    p_canonical_target TEXT,
    p_payload_hash TEXT,
    p_payload JSONB,
    p_outbox_logical_identity_hash TEXT,
    p_outbox_source_event_id TEXT,
    p_outbox_notification_type TEXT,
    p_outbox_recipient_identity TEXT,
    p_outbox_payload_template JSONB
) RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_existing_type TEXT;
    v_existing_target TEXT;
    v_existing_hash TEXT;
    v_existing_result JSONB;
    v_result JSONB;
    
    v_ticket_owner BIGINT;
    v_actual_customer_id BIGINT;
    v_existing_desc TEXT;
    v_current_status TEXT;
    v_timestamp TEXT;
    
    v_cust_email TEXT;
    v_cust_name TEXT;
    v_final_outbox_payload JSONB;
    v_ticket_id BIGINT;
BEGIN
    -- Derive actual customer_id if p_customer_id is NULL (agent update)
    IF p_operation_type = 'update_ticket' THEN
        v_ticket_id := p_canonical_target::BIGINT;
        -- Lock ticket to derive authoritative ticket.customer_id
        SELECT customer_id INTO v_ticket_owner FROM tickets WHERE id = v_ticket_id FOR UPDATE;
        IF NOT FOUND THEN
            RETURN jsonb_build_object('error', 'Ticket #' || v_ticket_id || ' not found');
        END IF;
        IF p_customer_id IS NOT NULL AND v_ticket_owner != p_customer_id THEN
            RETURN jsonb_build_object('error', 'Ticket #' || v_ticket_id || ' does not belong to you');
        END IF;
        v_actual_customer_id := v_ticket_owner;
    ELSE
        IF p_customer_id IS NULL THEN
            RETURN jsonb_build_object('error', 'Customer ID is required for ticket creation');
        END IF;
        v_actual_customer_id := p_customer_id;
    END IF;

    -- 1. Idempotency Lookup
    SELECT operation_type, canonical_target, payload_hash, terminal_result
    INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
    FROM idempotency_records
    WHERE customer_id = v_actual_customer_id AND client_request_id = p_client_request_id
    FOR UPDATE;

    IF FOUND THEN
        IF v_existing_type != p_operation_type OR v_existing_target != p_canonical_target OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object(
                'error', 'IdempotencyConflict',
                'message', 'This request ID was already used for a different operation.',
                'previous_result', v_existing_result
            );
        END IF;
        -- EXACT_REPLAY: return cached result, do NOT insert outbox
        RETURN v_existing_result;
    END IF;

    -- 2. Insert Idempotency Record
    BEGIN
        INSERT INTO idempotency_records (
            customer_id, client_request_id, operation_type, canonical_target, payload_hash
        ) VALUES (
            v_actual_customer_id, p_client_request_id, p_operation_type, p_canonical_target, p_payload_hash
        );
    EXCEPTION WHEN unique_violation THEN
        SELECT operation_type, canonical_target, payload_hash, terminal_result
        INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
        FROM idempotency_records
        WHERE customer_id = v_actual_customer_id AND client_request_id = p_client_request_id
        FOR UPDATE;
        
        IF v_existing_type != p_operation_type OR v_existing_target != p_canonical_target OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object('error', 'IdempotencyConflict', 'previous_result', v_existing_result);
        END IF;
        RETURN v_existing_result;
    END;

    -- 3. Business Mutation
    IF p_operation_type = 'create_ticket' THEN
        INSERT INTO tickets (
            customer_id, subject, description, type, status, priority, channel, order_id
        ) VALUES (
            v_actual_customer_id,
            p_payload->>'subject',
            p_payload->>'description',
            p_payload->>'type',
            p_payload->>'status',
            p_payload->>'priority',
            p_payload->>'channel',
            (p_payload->>'order_id')::BIGINT
        ) RETURNING id INTO v_ticket_id;
        
        v_result := jsonb_build_object(
            'status', 'success',
            'message', 'Ticket #' || v_ticket_id || ' created successfully',
            'ticket_id', v_ticket_id
        );

        -- Enqueue Outbox for Create
        IF p_outbox_logical_identity_hash IS NOT NULL THEN
            SELECT email, name INTO v_cust_email, v_cust_name FROM customers WHERE id = v_actual_customer_id;
            v_final_outbox_payload := p_outbox_payload_template || jsonb_build_object(
                'ticket_id', v_ticket_id,
                'customer_name', v_cust_name
            );
            
            PERFORM enqueue_outbox_event(
                p_outbox_logical_identity_hash,
                p_outbox_source_event_id,
                p_outbox_notification_type,
                p_outbox_recipient_identity,
                v_cust_email,
                v_final_outbox_payload
            );
        END IF;

    ELSIF p_operation_type = 'update_ticket' THEN
        SELECT description, status INTO v_existing_desc, v_current_status
        FROM tickets WHERE id = v_ticket_id FOR UPDATE;
        
        IF p_payload ? 'description_append' THEN
            v_timestamp := to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS "UTC"');
            v_existing_desc := COALESCE(v_existing_desc, '') || E'\n\n--- Update (' || v_timestamp || E') ---\n' || (p_payload->>'description_append');
        END IF;
        
        UPDATE tickets SET 
            description = v_existing_desc,
            priority = COALESCE(p_payload->>'priority', priority),
            order_id = COALESCE((p_payload->>'order_id')::BIGINT, order_id),
            status = COALESCE(p_payload->>'status', status),
            resolution = COALESCE(p_payload->>'resolution', resolution),
            assigned_agent = COALESCE(p_payload->>'assigned_agent', assigned_agent),
            satisfaction_rating = COALESCE((p_payload->>'satisfaction_rating')::INT, satisfaction_rating),
            closed_at = CASE WHEN (p_payload->>'status' = 'closed' AND v_current_status != 'closed') THEN now() ELSE closed_at END,
            updated_at = now()
        WHERE id = v_ticket_id;
        
        v_result := jsonb_build_object('status', 'success', 'message', 'Ticket #' || v_ticket_id || ' updated');

        -- Enqueue Outbox for Resolution
        IF (p_payload->>'status' = 'closed' AND v_current_status != 'closed' AND p_outbox_logical_identity_hash IS NOT NULL) THEN
            SELECT email, name INTO v_cust_email, v_cust_name FROM customers WHERE id = v_actual_customer_id;
            v_final_outbox_payload := p_outbox_payload_template || jsonb_build_object(
                'ticket_id', v_ticket_id,
                'customer_name', v_cust_name
            );
            
            IF p_outbox_logical_identity_hash = 'GENERATED_IN_SQL' THEN
                PERFORM enqueue_outbox_event(
                    md5('customer:' || v_actual_customer_id || '|req:' || p_client_request_id || '|TICKET_RESOLVED|customer:' || v_actual_customer_id),
                    'customer:' || v_actual_customer_id || '|req:' || p_client_request_id,
                    'TICKET_RESOLVED',
                    'customer:' || v_actual_customer_id,
                    v_cust_email,
                    v_final_outbox_payload
                );
            ELSE
                PERFORM enqueue_outbox_event(
                    p_outbox_logical_identity_hash,
                    p_outbox_source_event_id,
                    p_outbox_notification_type,
                    p_outbox_recipient_identity,
                    v_cust_email,
                    v_final_outbox_payload
                );
            END IF;
        END IF;
    ELSE
        v_result := jsonb_build_object('error', 'Unknown operation type: ' || p_operation_type);
    END IF;

    -- 4. Save Terminal Result
    IF NOT (v_result ? 'error') THEN
        UPDATE idempotency_records 
        SET terminal_result = v_result
        WHERE customer_id = v_actual_customer_id AND client_request_id = p_client_request_id;
    END IF;

    RETURN v_result;
END;
$$;

REVOKE EXECUTE ON FUNCTION execute_ticket_mutation_with_outbox FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION execute_ticket_mutation_with_outbox TO service_role;

-- 9. Durable Escalation State (Slice 3.5)
CREATE TABLE IF NOT EXISTS session_escalation_state (
    session_id TEXT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'NONE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_status CHECK (status IN ('NONE', 'ACTIVE', 'RELEASED'))
);

ALTER TABLE public.session_escalation_state ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.session_escalation_state FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.session_escalation_state TO service_role;

-- 10. Escalation Events (Slice 3.5.2)
CREATE TABLE IF NOT EXISTS escalation_events (
    escalation_event_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES session_escalation_state(session_id),
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    ticket_id BIGINT REFERENCES tickets(id) ON DELETE SET NULL,
    client_request_id UUID NOT NULL,
    payload_hash TEXT NOT NULL,
    sentiment TEXT,
    urgency TEXT,
    last_message TEXT,
    customer_notification_required BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.escalation_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.escalation_events FROM anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.escalation_events TO service_role;


-- 11. Escalation Transaction RPC (Slice 3.5.2)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION execute_escalation_transition(
    p_customer_id BIGINT,
    p_client_request_id UUID,
    p_session_id TEXT,
    p_payload_hash TEXT,
    p_payload JSONB,
    p_escalation_event_id UUID
) RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_existing_type TEXT;
    v_existing_target TEXT;
    v_existing_hash TEXT;
    v_existing_result JSONB;
    
    v_state_customer_id BIGINT;
    v_current_status TEXT;
    
    v_result JSONB;
    v_cust_email TEXT;
    v_cust_name TEXT;
    v_support_email TEXT := 'support@example.com'; -- fallback/template logic
    
    v_support_identity_string TEXT;
    v_support_outbox_hash TEXT;
    
    v_customer_identity_string TEXT;
    v_customer_outbox_hash TEXT;
BEGIN
    -- 1. Lock the single durable escalation-state row
    SELECT customer_id, status INTO v_state_customer_id, v_current_status
    FROM session_escalation_state
    WHERE session_id = p_session_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('error', 'Session state not initialized for ' || p_session_id);
    END IF;

    -- 2. Authorization
    IF v_state_customer_id != p_customer_id THEN
        RETURN jsonb_build_object('error', 'Session belongs to a different customer.');
    END IF;

    -- 3. Request Idempotency Validation (escalate_session)
    SELECT operation_type, canonical_target, payload_hash, terminal_result
    INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
    FROM idempotency_records
    WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id
    FOR UPDATE;

    IF FOUND THEN
        IF v_existing_type != 'escalate_session' OR v_existing_target != p_session_id OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object(
                'error', 'IdempotencyConflict',
                'message', 'Request ID already used for a different operation/payload.',
                'previous_result', v_existing_result
            );
        END IF;
        -- EXACT REPLAY
        RETURN v_existing_result;
    END IF;

    -- Insert Idempotency Record
    BEGIN
        INSERT INTO idempotency_records (
            customer_id, client_request_id, operation_type, canonical_target, payload_hash
        ) VALUES (
            p_customer_id, p_client_request_id, 'escalate_session', p_session_id, p_payload_hash
        );
    EXCEPTION WHEN unique_violation THEN
        SELECT operation_type, canonical_target, payload_hash, terminal_result
        INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
        FROM idempotency_records
        WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id
        FOR UPDATE;
        
        IF v_existing_type != 'escalate_session' OR v_existing_target != p_session_id OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object('error', 'IdempotencyConflict', 'previous_result', v_existing_result);
        END IF;
        RETURN v_existing_result;
    END;

    -- 4. Lifecycle transition validation
    IF v_current_status = 'ACTIVE' THEN
        -- Bypassed
        v_result := jsonb_build_object(
            'status', 'bypassed',
            'message', 'Session is already ACTIVE. Escalation bypassed.',
            'session_id', p_session_id
        );
    ELSIF v_current_status = 'NONE' OR v_current_status = 'RELEASED' THEN
        -- E1 or E2: Insert Event
        INSERT INTO escalation_events (
            escalation_event_id, session_id, customer_id, ticket_id, client_request_id, payload_hash,
            sentiment, urgency, last_message, customer_notification_required
        ) VALUES (
            p_escalation_event_id,
            p_session_id,
            p_customer_id,
            (p_payload->>'ticket_id')::BIGINT,
            p_client_request_id,
            p_payload_hash,
            p_payload->>'sentiment',
            p_payload->>'urgency',
            p_payload->>'last_message',
            (p_payload->>'customer_notification_required')::BOOLEAN
        );

        -- Update State
        UPDATE session_escalation_state
        SET status = 'ACTIVE', updated_at = NOW()
        WHERE session_id = p_session_id;

        -- Generate authoritative Slice 3.1 LogicalNotificationIdentity hashes internally
        v_support_identity_string := '["v1","escalation:' || p_escalation_event_id::TEXT || '","ESCALATION_TEAM","support-team:default"]';
        v_support_outbox_hash := encode(digest(v_support_identity_string, 'sha256'), 'hex');

        -- Outbox Support Notification
        PERFORM enqueue_outbox_event(
            v_support_outbox_hash,
            p_escalation_event_id::TEXT,
            'ESCALATION_TEAM',
            'support_team',
            v_support_email,
            jsonb_build_object(
                'session_id', p_session_id,
                'sentiment', p_payload->>'sentiment',
                'urgency', p_payload->>'urgency',
                'ticket_id', p_payload->>'ticket_id',
                'customer_id', p_customer_id
            )
        );

        -- Conditionally Enqueue Customer Outbox Notification
        IF (p_payload->>'customer_notification_required')::BOOLEAN THEN
            v_customer_identity_string := '["v1","escalation:' || p_escalation_event_id::TEXT || '","ESCALATION_CUSTOMER","customer:' || p_customer_id::TEXT || '"]';
            v_customer_outbox_hash := encode(digest(v_customer_identity_string, 'sha256'), 'hex');

            SELECT email, name INTO v_cust_email, v_cust_name FROM customers WHERE id = p_customer_id;
            PERFORM enqueue_outbox_event(
                v_customer_outbox_hash,
                p_escalation_event_id::TEXT,
                'ESCALATION_CUSTOMER',
                'customer:' || p_customer_id,
                v_cust_email,
                jsonb_build_object(
                    'session_id', p_session_id,
                    'customer_name', v_cust_name
                )
            );
        END IF;

        v_result := jsonb_build_object(
            'status', 'success',
            'message', 'Escalation triggered successfully.',
            'escalation_event_id', p_escalation_event_id,
            'session_id', p_session_id
        );
    ELSE
        v_result := jsonb_build_object('error', 'Unknown status: ' || v_current_status);
    END IF;

    -- 5. Save Terminal Result
    IF NOT (v_result ? 'error') THEN
        UPDATE idempotency_records 
        SET terminal_result = v_result
        WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id;
    END IF;

    RETURN v_result;
END;
$$;

REVOKE EXECUTE ON FUNCTION execute_escalation_transition FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION execute_escalation_transition TO service_role;

-- 12. Durable Release Transaction RPC (Slice 3.5.4)
CREATE OR REPLACE FUNCTION execute_release_transition(
    p_customer_id BIGINT,
    p_client_request_id UUID,
    p_session_id TEXT,
    p_payload_hash TEXT,
    p_payload JSONB
) RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_existing_type TEXT;
    v_existing_target TEXT;
    v_existing_hash TEXT;
    v_existing_result JSONB;
    
    v_state_customer_id BIGINT;
    v_current_status TEXT;
    v_result JSONB;
BEGIN
    -- 1. Lock the single durable escalation-state row
    SELECT customer_id, status INTO v_state_customer_id, v_current_status
    FROM session_escalation_state
    WHERE session_id = p_session_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('error', 'Session state not initialized for ' || p_session_id);
    END IF;

    -- 2. Authorization
    IF v_state_customer_id != p_customer_id THEN
        RETURN jsonb_build_object('error', 'Session belongs to a different customer.');
    END IF;

    -- 3. Idempotency Validation (release_session)
    SELECT operation_type, canonical_target, payload_hash, terminal_result
    INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
    FROM idempotency_records
    WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id
    FOR UPDATE;

    IF FOUND THEN
        IF v_existing_type != 'release_session' OR v_existing_target != p_session_id OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object(
                'error', 'IdempotencyConflict',
                'message', 'Request ID already used for a different operation/payload.',
                'previous_result', v_existing_result
            );
        END IF;
        -- EXACT REPLAY
        RETURN v_existing_result;
    END IF;

    -- Insert Idempotency Record
    BEGIN
        INSERT INTO idempotency_records (
            customer_id, client_request_id, operation_type, canonical_target, payload_hash
        ) VALUES (
            p_customer_id, p_client_request_id, 'release_session', p_session_id, p_payload_hash
        );
    EXCEPTION WHEN unique_violation THEN
        SELECT operation_type, canonical_target, payload_hash, terminal_result
        INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
        FROM idempotency_records
        WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id
        FOR UPDATE;
        
        IF v_existing_type != 'release_session' OR v_existing_target != p_session_id OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object('error', 'IdempotencyConflict', 'previous_result', v_existing_result);
        END IF;
        RETURN v_existing_result;
    END;

    -- 4. Lifecycle transition validation
    IF v_current_status = 'RELEASED' THEN
        -- Deterministic already-released
        v_result := jsonb_build_object(
            'status', 'success',
            'message', 'Session is already RELEASED.',
            'session_id', p_session_id
        );
    ELSIF v_current_status = 'NONE' THEN
        v_result := jsonb_build_object(
            'error', 'Cannot release a session that is not escalated.',
            'status', 'failed'
        );
    ELSIF v_current_status = 'ACTIVE' THEN
        -- Mutate durable state
        UPDATE session_escalation_state
        SET status = 'RELEASED', updated_at = NOW()
        WHERE session_id = p_session_id;

        v_result := jsonb_build_object(
            'status', 'success',
            'message', 'Session released successfully.',
            'session_id', p_session_id
        );
    END IF;

    -- 5. Terminal Idempotency Result
    UPDATE idempotency_records
    SET terminal_result = v_result
    WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id;

    RETURN v_result;
END;
$$;

REVOKE EXECUTE ON FUNCTION execute_release_transition FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION execute_release_transition TO service_role;


-- 9. Custom Email Outbox Event RPC (Slice 3.6)
CREATE OR REPLACE FUNCTION enqueue_custom_email_outbox_event(
    p_customer_id BIGINT,
    p_client_request_id UUID,
    p_ticket_id BIGINT,
    p_recipient_email TEXT,
    p_payload JSONB,
    p_payload_hash TEXT,
    p_outbox_logical_identity_hash TEXT,
    p_outbox_source_event_id TEXT,
    p_outbox_notification_type TEXT,
    p_outbox_recipient_identity TEXT
) RETURNS JSONB
LANGUAGE plpgsql
AS $$
DECLARE
    v_ticket_owner BIGINT;
    v_payload JSONB;
    v_payload_hash TEXT;
    v_source_event_id TEXT;
    v_logical_identity TEXT;
    v_logical_identity_hash TEXT;
    v_existing_type TEXT;
    v_existing_target TEXT;
    v_existing_hash TEXT;
    v_existing_result JSONB;
    v_outbox_event_id UUID;
    v_result JSONB;
BEGIN
    -- 1. Verify Ticket Ownership
    SELECT customer_id INTO v_ticket_owner
    FROM tickets WHERE id = p_ticket_id;
    
    IF NOT FOUND OR v_ticket_owner != p_customer_id THEN
        RETURN jsonb_build_object('error', 'Ticket #' || p_ticket_id || ' not found or does not belong to you');
    END IF;

    -- The canonical hashes (idempotency p_payload_hash and outbox p_outbox_logical_identity_hash)
    -- are computed in Python to preserve the single canonicalization convention.
    
    -- 3. Idempotency Check (Row Lock)
    SELECT operation_type, canonical_target, payload_hash, terminal_result
    INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
    FROM idempotency_records
    WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id
    FOR UPDATE;

    IF FOUND THEN
        IF v_existing_type != 'custom_email' OR v_existing_target != p_ticket_id::TEXT OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object(
                'error', 'IdempotencyConflict',
                'message', 'This request ID was already used for a different operation.',
                'previous_result', v_existing_result
            );
        END IF;
        RETURN v_existing_result;
    END IF;

    -- 4. Insert to establish operation and claim the request_id.
    BEGIN
        INSERT INTO idempotency_records (
            customer_id, client_request_id, operation_type, canonical_target, payload_hash, terminal_result
        ) VALUES (
            p_customer_id, p_client_request_id, 'custom_email', p_ticket_id::TEXT, p_payload_hash, NULL
        );
    EXCEPTION WHEN unique_violation THEN
        SELECT operation_type, canonical_target, payload_hash, terminal_result
        INTO v_existing_type, v_existing_target, v_existing_hash, v_existing_result
        FROM idempotency_records
        WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id
        FOR UPDATE;
        
        IF v_existing_type != 'custom_email' OR v_existing_target != p_ticket_id::TEXT OR v_existing_hash != p_payload_hash THEN
            RETURN jsonb_build_object(
                'error', 'IdempotencyConflict',
                'message', 'This request ID was already used for a different operation.',
                'previous_result', v_existing_result
            );
        END IF;
        RETURN v_existing_result;
    END;

    -- 5. Create outbox event
    INSERT INTO outbox_events (
        logical_identity_hash, source_event_id, notification_type, 
        recipient_identity, recipient_address, payload, status
    ) VALUES (
        p_outbox_logical_identity_hash, p_outbox_source_event_id, p_outbox_notification_type, 
        p_outbox_recipient_identity, p_recipient_email, p_payload, 'PENDING'
    )
    ON CONFLICT (logical_identity_hash) DO NOTHING
    RETURNING event_id INTO v_outbox_event_id;

    v_result := jsonb_build_object(
        'status', 'success',
        'message', 'Custom email to ' || p_recipient_email || ' enqueued successfully',
        'outbox_event_id', v_outbox_event_id
    );

    -- 6. Save terminal result
    UPDATE idempotency_records
    SET terminal_result = v_result
    WHERE customer_id = p_customer_id AND client_request_id = p_client_request_id;
    
    RETURN v_result;
END;
$$;

REVOKE EXECUTE ON FUNCTION enqueue_custom_email_outbox_event FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION enqueue_custom_email_outbox_event TO service_role;

-- Force PostgREST to reload schema cache so changes are immediately visible
NOTIFY pgrst, 'reload schema';
